# Generated by Django 5.2.5 on 2025-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='avaliable_seats',
        ),
        migrations.AddField(
            model_name='travel',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
